version = 0.1
[default.deploy.parameters]
stack_name = "sam-envmap"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1avr0ylgvc8ng"
s3_prefix = "sam-envmap"
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
confirm_changeset = true
